services:
  jumper:
    build:
      context: ./${JUMPER}
      args:
        - BASH_IMG=${BASH_IMG}
        - SSH_ROOT=${SSH_ROOT}
    image: ${JUMPER_IMG}
    container_name: ${JUMPER}
    hostname: ${JUMPER}
    stdin_open: true
    tty: true
    volumes:
      - shared-ssh:/root/.ssh
    networks:
      - ${JUMP_AREA}
  proxy:
    image: ${PROXY_IMG}
    container_name: ${PROXY}
    environment:
      - ALLOW_START=${FALSE} #optional
      - ALLOW_STOP=${FALSE} #optional
      - ALLOW_RESTARTS=${FALSE} #optional
      - AUTH=${FALSE} #optional
      - BUILD=${FALSE} #optional
      - COMMIT=${FALSE} #optional
      - CONFIGS=${FALSE} #optional
      - CONTAINERS=${FALSE} #optional
      - DISABLE_IPV6=${FALSE} #optional
      - DISTRIBUTION=${FALSE} #optional
      - EVENTS=${TRUE} #optional
      - EXEC=${FALSE} #optional
      - IMAGES=${FALSE} #optional
      - INFO=${FALSE} #optional
      - NETWORKS=${FALSE} #optional
      - NODES=${FALSE} #optional
      - PING=${TRUE} #optional
      - POST=${FALSE} #optional
      - PLUGINS=${FALSE} #optional
      - SECRETS=${FALSE} #optional
      - SERVICES=${FALSE} #optional
      - SESSION=${FALSE} #optional
      - SWARM=${FALSE} #optional
      - SYSTEM=${FALSE} #optional
      - TASKS=${FALSE} #optional
      - TAG=${TRUE} #optional
      - VOLUMES=${FALSE} #optional
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH}:ro
    networks:
      - ${PROXIFIED_SOCKET}
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
  controller:
    build:
      context: ./${CONTROLLER}
      args:
        - BASH_IMG=${BASH_IMG}
        - DOCKER_IMG=${DOCKER_IMG}
    image: ${CONTROLLER_IMG}
    container_name: ${CONTROLLER}
    hostname: ${CONTROLLER}
    environment:
      - DOCKER_HOST=tcp://${PROXY}:${PROXY_PORT}
    stdin_open: true
    tty: true
    volumes:
      - shared-ssh:/root/.ssh
    networks:
      - ${PROXIFIED_SOCKET}
      - ${JUMP_AREA}

networks:
  proxy_for_controller:
    driver: bridge
    name: ${PROXIFIED_SOCKET}
    ipam:
      driver: default
  jump_area:
    driver: bridge
    name: ${JUMP_AREA}
    ipam:
      driver: default

volumes:
  shared-ssh:
    name: shared-ssh
