services:
  jumper:
    build:
      context: ./${JUMPER}
      args:
        - BASH_IMG=${BASH_IMG}
        - SSH_ROOT=${SSH_ROOT}
    image: ${JUMPER_IMG}
    container_name: ${JUMPER}
    hostname: ${JUMPER}
    stdin_open: true
    tty: true
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT}
    networks:
      - ${JUMP_AREA}
  proxy:
    build:
      context: ./${PROXY}
      args:
        - API_ENDPOINT_VERSION=${TRUE}
        - DOCKER_IMG=${DOCKER_IMG}
        - PROXY_PORT=${PROXY_PORT}
        - OS=${OS}
        - TMP_NGX=/tmp/nginx
        - SOCKET_PATH=${SOCKET_PATH}
    image: ${PROXY_IMG}
    container_name: ${PROXY}
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH}:ro
    networks:
      - ${PROXIFIED_SOCKET}
    read_only: true
    tmpfs:
      - /run
  controller:
    build:
      context: ./${CONTROLLER}
      args:
        - BASH_IMG=${BASH_IMG}
        - DOCKER_HOST=tcp://${PROXY}:${PROXY_PORT}
        - DOCKER_IMG=${DOCKER_IMG}
    image: ${CONTROLLER_IMG}
    container_name: ${CONTROLLER}
    hostname: ${CONTROLLER}
    stdin_open: true
    tty: true
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT}
    networks:
      - ${PROXIFIED_SOCKET}
      - ${JUMP_AREA}

networks:
  proxy_for_controller:
    driver: bridge
    name: ${PROXIFIED_SOCKET}
    ipam:
      driver: default
  jump_area:
    driver: bridge
    name: ${JUMP_AREA}
    ipam:
      driver: default

volumes:
  shared-ssh:
    name: ${SSH_VOLUME}
