services:
  proxy:
    build:
      context: ./${PROXY_ID}
      args:
        - APK_PATHS=${APK_PATHS}
        - API_SFX=${API_SFX}
        - API_URL=${API_URL}
        - ${API_SFX}NETWORKS=${TRUE}
        - ${API_SFX}VERSION=${TRUE}
        - DOCKER_IMG=${DOCKER_IMG}
        - DOCKER_PATH=${DOCKER_PATH}
        - ENTRYPOINT_PATH=${ENTRYPOINT_PATH}
        - ETC_NGX_PATH=${ETC_NGX_PATH}
        - LINUXSERVER_PROXY_IMG=${LINUXSERVER_PROXY_IMG}
        - NET=${JUMP_AREA_NET}
        - OS_IMG=${OS_IMG}
        - OPT_SCRIPTS_PATH=${OPT_SCRIPTS_PATH}
        - PROXY_PORT=${PROXY_PORT}
        - SOCKET_PATH=${SOCKET_PATH}
        - TMP_NGX_PATH=/tmp/nginx
        - TMP_WARNING_PATH=/tmp/api/warning
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${PROXY_IMG}
    container_name: ${PROXY_ID}
    hostname: ${PROXY_ID}
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH}:ro
      - ${PROXY_FS_VOLUME}:${ETC_NGX_PATH}:ro
    networks:
      - ${PROXIFIED_SOCKET_NET}
    read_only: true
    tmpfs:
      - /run
  collector:
    depends_on:
      - ${PROXY_ID}
    build:
      context: ./${COLLECTOR_ID}
      args:
        - APK_PATHS=${APK_PATHS}
        - COMPLETION_PATH=${COMPLETION_PATH}
        - CRON_LOG_PATH=${CRON_LOG_PATH}
        - CRONTABS_PATH=${CRONTABS_PATH}
        - DATA_PATH=${DATA_PATH}
        - ENTRYPOINT_PATH=${ENTRYPOINT_PATH}
        - HTTP_DOCKER_HOST=${HTTP_DOCKER_HOST}
        - NET=${JUMP_AREA_NET}
        - OPT_SCRIPTS_PATH=${OPT_SCRIPTS_PATH}
        - OS_IMG=${OS_IMG}
        - PROXY_ID=${PROXY_ID}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${COLLECTOR_IMG}
    container_name: ${COLLECTOR_ID}
    hostname: ${COLLECTOR_ID}
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT_PATH}:ro
      - ${COLLECTOR_ETC_CRONTABS_VOLUME}:${CRONTABS_PATH}:ro
      - ${COLLECTOR_OPT_DATA_VOLUME}:${DATA_PATH}:rw
      - ${COLLECTOR_OPT_SCRIPTS_VOLUME}:${OPT_SCRIPTS_PATH}:ro
      - ${COLLECTOR_VAR_LOG_VOLUME}:${VAR_LOG_PATH}:rw
    networks:
      - ${PROXIFIED_SOCKET_NET}
    read_only: true
  controller:
    depends_on:
      - ${PROXY_ID}
    build:
      context: ./${CONTROLLER_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - DOCKER_IMG=${DOCKER_IMG}
        - DOCKER_PATH=${DOCKER_PATH}
        - ENTRYPOINT_PATH=${ENTRYPOINT_PATH}
        - NET=${JUMP_AREA_NET}
        - OPT_SCRIPTS_PATH=${OPT_SCRIPTS_PATH}
        - TCP_DOCKER_HOST=${TCP_DOCKER_HOST}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${CONTROLLER_IMG}
    container_name: ${CONTROLLER_ID}
    hostname: ${CONTROLLER_ID}
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT_PATH}:ro
    networks:
      - ${PROXIFIED_SOCKET_NET}
      - ${JUMP_AREA_NET}
  jumper:
    depends_on:
      - ${COLLECTOR_ID}
    build:
      context: ./${JUMPER_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - COMPLETION_PATH=/opt/${COLLECTOR_ID}${COMPLETION_PATH}
        - CONTROLLER_ID=${CONTROLLER_ID}
        - ENTRYPOINT_PATH=${ENTRYPOINT_PATH}
        - HOSTNAME=${JUMPER_ID}
        - NET=${JUMP_AREA_NET}
        - OPT_SCRIPTS_PATH=${OPT_SCRIPTS_PATH}
        - OPT_SSH_PATH=${OPT_SSH_PATH}
        - SSH_ROOT_PATH=${SSH_ROOT_PATH}
        - TCP_DOCKER_HOST=${TCP_DOCKER_HOST}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${JUMPER_IMG}
    container_name: ${JUMPER_ID}
    hostname: ${JUMPER_ID}
    volumes:
      - ${SSH_VOLUME}:${OPT_SSH_PATH}:ro
      - ${PROXY_FS_VOLUME}:/opt/${PROXY_ID}${ETC_NGX_PATH}:ro
      - ${COLLECTOR_ETC_CRONTABS_VOLUME}:/opt/${COLLECTOR_ID}${CRONTABS_PATH}:ro
      - ${COLLECTOR_OPT_DATA_VOLUME}:/opt/${COLLECTOR_ID}${DATA_PATH}:ro
      - ${COLLECTOR_OPT_SCRIPTS_VOLUME}:/opt/${COLLECTOR_ID}${OPT_SCRIPTS_PATH}:ro
      - ${COLLECTOR_VAR_LOG_VOLUME}:/opt/${COLLECTOR_ID}${VAR_LOG_PATH}:ro
    networks:
      - ${JUMP_AREA_NET}
    stdin_open: true
    tty: true
  editor:
    build:
      context: ./${EDITOR_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - ENTRYPOINT_PATH=${ENTRYPOINT_PATH}
        - NET=${JUMP_AREA_NET}
        - OPT_SCRIPTS_PATH=${OPT_SCRIPTS_PATH}
        - WORKSPACES_PATH=${WORKSPACES_PATH}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${EDITOR_IMG}
    container_name: ${EDITOR_ID}
    hostname: ${EDITOR_ID}
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT_PATH}:ro
      - ${MY_WHALE_FLEET_VOLUME}:${MY_WHALE_FLEET_PATH}:rw
    networks:
      - ${JUMP_AREA_NET}

networks:
  proxy_for_controller:
    driver: bridge
    name: ${PROXIFIED_SOCKET_NET}
    ipam:
      driver: default
  jump_area:
    driver: bridge
    name: ${JUMP_AREA_NET}
    ipam:
      driver: default

volumes:
  shared-ssh:
    name: ${SSH_VOLUME}
  my-whale-fleet:
    name: ${MY_WHALE_FLEET_VOLUME}
  proxy-fs:
    name: ${PROXY_FS_VOLUME}
  collector-etc-crontabs-fs:
    name: ${COLLECTOR_ETC_CRONTABS_VOLUME}
  collector-opt-data-fs:
    name: ${COLLECTOR_OPT_DATA_VOLUME}
  collector-opt-scripts-fs:
    name: ${COLLECTOR_OPT_SCRIPTS_VOLUME}
  collector-var-log-fs:
    name: ${COLLECTOR_VAR_LOG_VOLUME}
