services:
  proxy:
    build:
      context: ./${PROXY_ID}
      args:
        - API_SFX=${API_SFX}
        - API_URL=${API_URL}
        - ${API_SFX}NETWORKS=${TRUE}
        - ${API_SFX}VERSION=${TRUE}
        - DOCKER_IMG=${DOCKER_IMG}
        - DOCKER_PATH=${DOCKER_PATH}
        - ETC_NGX_PATH=/etc/nginx
        - LINUXSERVER_PROXY_IMG=${LINUXSERVER_PROXY_IMG}
        - NET=${JUMP_AREA_NET}
        - OS_IMG=${OS_IMG}
        - PROXY_PORT=${PROXY_PORT}
        - SOCKET_PATH=${SOCKET_PATH}
        - TMP_NGX_PATH=/tmp/nginx
        - TMP_WARNING_PATH=/tmp/api/warning
        - UNPRIVILEGED_USER=${UNPRIVILEGED_USER}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${PROXY_IMG}
    container_name: ${PROXY_ID}
    hostname: ${PROXY_ID}
    volumes:
      - ${SOCKET_PATH}:${SOCKET_PATH}:ro
      - ${SSH_VOLUME}:/home/${UNPRIVILEGED_USER}/.ssh:ro
    networks:
      - ${PROXIFIED_SOCKET_NET}
      - ${JUMP_AREA_NET}
    read_only: true
    tmpfs:
      - /run
  controller:
    depends_on:
      - ${PROXY_ID}
    build:
      context: ./${CONTROLLER_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - CACHE_PATH=${CACHE_PATH}
        - CACHE_COMPLETION_PATH=${CACHE_COMPLETION_PATH}
        - DOCKER_HOST=tcp://${PROXY_ID}:${PROXY_PORT}
        - DOCKER_IMG=${DOCKER_IMG}
        - DOCKER_PATH=${DOCKER_PATH}
        - MY_WHALE_FLEET_PATH=${MY_WHALE_FLEET_PATH}
        - NET=${JUMP_AREA_NET}
        - SSH_ROOT_PATH=${SSH_ROOT_PATH}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${CONTROLLER_IMG}
    container_name: ${CONTROLLER_ID}
    hostname: ${CONTROLLER_ID}
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT_PATH}:ro
      - ${CACHE_VOLUME}:${CACHE_PATH}:rw
      - ${MY_WHALE_FLEET_VOLUME}:${MY_WHALE_FLEET_PATH}:ro
    networks:
      - ${PROXIFIED_SOCKET_NET}
      - ${JUMP_AREA_NET}
  jumper:
    build:
      context: ./${JUMPER_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - CACHE_PATH=${CACHE_PATH}
        - CACHE_COMPLETION_PATH=${CACHE_COMPLETION_PATH}
        - CONTROLLER_ID=${CONTROLLER_ID}
        - DOCKER_HOST=tcp://${PROXY_ID}:${PROXY_PORT}
        - HOSTNAME=${JUMPER_ID}
        - NET=${JUMP_AREA_NET}
        - OPT_SSH_PATH=${OPT_SSH_PATH}
        - SSH_ROOT_PATH=${SSH_ROOT_PATH}
        - UNPRIVILEGED_USER=${UNPRIVILEGED_USER}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${JUMPER_IMG}
    container_name: ${JUMPER_ID}
    hostname: ${JUMPER_ID}
    volumes:
      - ${SSH_VOLUME}:${OPT_SSH_PATH}:ro
      - ${CACHE_VOLUME}:${CACHE_PATH}:ro
    networks:
      - ${JUMP_AREA_NET}
    stdin_open: true
    tty: true
  editor:
    build:
      context: ./${EDITOR_ID}
      args:
        - BASH_IMG=${BASH_IMG}
        - MY_WHALE_FLEET_PATH=${MY_WHALE_FLEET_PATH}
        - MY_WHALE_FLEET_URL=${MY_WHALE_FLEET_URL}
        - NET=${JUMP_AREA_NET}
        - WORKSPACES_PATH=${WORKSPACES_PATH}
        - HTTP_PROXY=${http_proxy:-${HTTP_PROXY:-}}
        - HTTPS_PROXY=${https_proxy:-${HTTPS_PROXY:-}}
    image: ${EDITOR_IMG}
    container_name: ${EDITOR_ID}
    hostname: ${EDITOR_ID}
    volumes:
      - ${SSH_VOLUME}:${SSH_ROOT_PATH}:ro
      - ${MY_WHALE_FLEET_VOLUME}:${MY_WHALE_FLEET_PATH}:rw
    networks:
      - ${JUMP_AREA_NET}

networks:
  proxy_for_controller:
    driver: bridge
    name: ${PROXIFIED_SOCKET_NET}
    ipam:
      driver: default
  jump_area:
    driver: bridge
    name: ${JUMP_AREA_NET}
    ipam:
      driver: default

volumes:
  shared-ssh:
    name: ${SSH_VOLUME}
  my-whale-fleet:
    name: ${MY_WHALE_FLEET_VOLUME}
  cache:
    name: ${CACHE_VOLUME}
