#!/bin/sh

OUTPUT_LEN='70'

SEP='#'

ERASE_UNTIL_END='\033[K'

GREEN='\033[38;5;2m'
GREEN2='\033[38;5;10m'
BLUE='\033[38;5;14m'
RED='\033[38;5;9m'
WHITE='\033[38;5;15m'
RESET='\033[m'
BOLD='\033[1m'
RAINBOW="\033[38;5;196m${SEP}\033[38;5;202m${SEP}\033[38;5;208m${SEP}\033[38;5;214m${SEP}\033[38;5;220m${SEP}\033[38;5;226m${SEP}\033[38;5;190m${SEP}\033[38;5;154m${SEP}\033[38;5;118m${SEP}\033[38;5;82m${SEP}\033[38;5;46m${SEP}\033[38;5;47m${SEP}\033[38;5;48m${SEP}\033[38;5;49m${SEP}\033[38;5;50m${SEP}\033[38;5;51m${SEP}\033[38;5;45m${SEP}\033[38;5;39m${SEP}\033[38;5;33m${SEP}\033[38;5;27m${SEP}\033[38;5;21m${SEP}\033[38;5;57m${SEP}\033[38;5;93m${SEP}\033[38;5;129m${SEP}\033[38;5;165m${SEP}\033[38;5;201m${SEP}\033[38;5;200m${SEP}\033[38;5;199m${SEP}\033[38;5;198m${SEP}\033[38;5;197m${SEP}"

MOVE_START_LINE='\033[G'
MOVE_TO_COLX="${MOVE_START_LINE}\033[${OUTPUT_LEN}C"

NL="$(printf '\nx')"
NL="${NL%?}"

NANOS='1000000000'

DEFAULT_SPEED='2'

SUDO='sudo -E'
SUDO_LIFETIME='290'

PM='apt'
ADD_REPO='add-apt-repository -y'
POLICY="${PM} policy"
INSTALL="${SUDO} ${PM} install -y"
UPDATE="${SUDO} ${PM} update -y"
UPGRADE="${SUDO} ${PM} upgrade -y"
AUTOREMOVE="${SUDO} ${PM} autoremove -y"

NOVERSION='unavailable'

ARCH="$(dpkg --print-architecture)"

LOCAL="${HOME}/.local"
LOCAL_SRC="${LOCAL}/src"
LOCAL_SH="${LOCAL}/sh"

POLYGLOT="${HOME}/.vim/pack/plugins/start/vim-polyglot"
TMUXPLUGINS="${HOME}/.tmux/plugins/tpm"
GITTEMPLATES='/usr/share/git-core/templates'

DOT="$(CDPATH= cd -- "$(dirname -- "${0}")" > /dev/null 2>&1 && pwd)"
DOT_VIMRC="${DOT}/vim/.vimrc"
DOT_TMUXCONF="${DOT}/tmux/.tmux.conf"
DOT_BASHRC="${DOT}/bash/.bashrc"
DOT_PROFILE="${DOT}/bash/.bash_profile"
DOT_ALIASES="${DOT}/bash/.bash_aliases"
DOT_GITIGNORE="${DOT}/git/.gitignore"
DOT_HOOKS="${DOT}/git/.hooks"
DOT_SH="${DOT}/sh"

readonly OUTPUT_LEN \
         SEP \
         ERASE_UNTIL_END \
         BLUE GREEN GREEN2 RED WHITE RESET BOLD RAINBOW \
         MOVE_START_LINE MOVE_TO_COLX \
         NL \
         NANOS \
         DEFAULT_SPEED \
         SUDO SUDO_LIFETIME \
         PM ADD_REPO POLICY INSTALL UPDATE UPGRADE AUTOREMOVE \
         NOVERSION \
         ARCH \
         LOCAL LOCAL_SRC DOT \
         DOT_VIMRC POLYGLOT DOT_TMUXCONF TMUXPLUGINS DOT_BASHRC DOT_PROFILE DOT_ALIASES DOT_GITIGNORE GITTEMPLATES DOT_HOOKS

_git ()
{
  if git --git-dir "${LOCAL_SRC}/${1}/.git" --work-tree "${LOCAL_SRC}/"${*}
  then
    return 0
  else
    return 1
  fi
}

dashed ()
{
  set -- "${1}" "${OUTPUT_LEN}" "${RAINBOW}" ''
  while [ ${2} -gt 0 ]
  do
    [ -z "${3}" ] && set -- "${1}" "${2}" "${RAINBOW}" "${4}"
    set -- "${1}" "$(( ${2} - 1 ))" "${3#*"${SEP}"}" "${4}${3%%"${SEP}"*}-"
  done
  set -- "${1}" "$(( ${#1} + 1 ))" "${4}"
  while [ ${2} -gt 0 ]
  do
    set -- "${1}" "$(( ${2} - 1 ))" "${3#*-}"
  done
  printf '%b%s%b %b%b ' "${WHITE}" "${1}" "${RESET}" "${3%\\*}" "${RESET}"
  return 0
}

# -- INPUT --
# 1) message
# 2) speed
dots ()
{
  trap 'DOTS_BREAK=""' USR1
  dashed "${1}"
  set -- "$(( $(date '+%s%N') * ${2} / NANOS ))" "${2}"
  set -- "${1}" "${@}"
  while [ -n "${DOTS_BREAK-x}" ]
  do
    set -- "${1}" "${2}" "${3}" "$(( $(date '+%s%N') * ${3} / NANOS ))"
    if [ $(( ${4} - ${1} )) -gt 0 ]
    then
      printf '%b%b.%b' "${WHITE}" "${BOLD}" "${RESET}"
      set -- "$(( $(date '+%s%N') * ${3} / NANOS ))" "${2}" "${3}" "${4}"
    fi
    if [ $(( ${4} - ${2} )) -gt 3 ]
    then
      printf '%b%b' "${MOVE_TO_COLX}" "${ERASE_UNTIL_END}"
      set -- "${1}" "$(( $(date '+%s%N') * ${3} / NANOS ))" "${3}" "${4}"
    fi
  done
  unset DOTS_BREAK
  return 0
}

stop_dots ()
{
  kill -USR1 "${1}"
  wait "${1}" || :
  printf '%b%b' "${MOVE_TO_COLX}" "${ERASE_UNTIL_END}"
  return 0
}

prompt_sudo ()
{
  if [ $(( $(date '+%s') - ${SUDO_LASTPROMPT:-0} )) -gt ${SUDO_LIFETIME} ]
  then
    sudo -k
    SUDO_LASTPROMPT="$(date '+%s')"
    ${SUDO} sh -c ':' || exit 1
  fi
  return 0
}

success ()
{
  printf '%b%bOK%b\n' "${GREEN}" "${BOLD}" "${RESET}"
  return 0
}

error ()
{
  printf '%b%bKO%b\n' "${RED}" "${BOLD}" "${RESET}"
  return 0
}

run ()
{
  dots "${1}" "${DEFAULT_SPEED}" &
  shift
  while [ ${#} -gt 0 ]
  do
    if [ -n "${NEED_EVAL-}" ]
    then
      if [ "${NEED_EVAL%"${NEED_EVAL#?}"}" = "${SEP}" ]
      then
        NEED_EVAL="${NEED_EVAL#"${SEP}"}"
      else
        if ! eval "${1}"
        then
          stop_dots "${!}"
          error
          exit 1
        fi
        NEED_EVAL="${NEED_EVAL#*"${SEP}"}"
        shift
        continue
      fi
    fi

    if ! ${1} > /dev/null 2>&1
    then
      stop_dots "${!}"
      error
      exit 1
    fi
    shift
  done
  stop_dots "${!}"
  success
  return 0
}

install ()
{
  while [ ${#} -gt 0 ]
  do
    dots "Checking ${1} package installation" "${DEFAULT_SPEED}" &
    case "$(dpkg -l)" in 
      *" ${1}"*) stop_dots "${!}"
              success ;;
      *) stop_dots "${!}"
         error
         prompt_sudo
         run "Installing ${1} package" "${INSTALL} ${1}" ;;
    esac
    shift
  done
  return 0
}

install_docker ()
{
  if [ ! -e "$(command -v docker)" ]
  then
    prompt_sudo
    curl -f -s -S -L https://download.docker.com/linux/ubuntu/gpg \
      | ${SUDO} gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    prompt_sudo
    printf 'deb [arch=%s signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu %s stable\n' "${ARCH}" "${RELEASE}" \
      | ${SUDO} tee /etc/apt/sources.list.d/docker.list > /dev/null
  fi
  return 0
}

git_install ()
{
  if [ ! -d "${LOCAL_SRC}/${1}" ]
  then
    NEED_EVAL= run "Cloning ${1} repository" "git clone ${2} ${LOCAL_SRC}/${1}"
    NEED_EVAL= run "Adding ${1} repository as a GIT safe repository" \
      "git config --global --add safe.directory ${LOCAL_SRC}/${1}"
    set -- '' '' '' '' "${@}"
  else
    NEED_EVAL= run "Adding ${1} repository as a GIT safe repository" \
      "git config --global --add safe.directory ${LOCAL_SRC}/${1}"
    NEED_EVAL= run "Moving to master branch into ${1} repository" \
      "_git ${1} checkout master"
    NEED_EVAL= run "Pulling ${1} repository" "_git ${1} pull"
    set -- "$(_git ${1} rev-list --tags --max-count=1)" "${@}"
    set -- "$(_git ${2} describe --tags "${1}")" "${@}"
    if [ -z "${NOTAG+x}${NOTAG-}" ]
    then
      NEED_EVAL= run "Moving to ${1} tag into ${3} repository" \
        "_git ${3} checkout ${1}"
    fi
    set -- "${1#"${1%%[[:digit:]]*}"}" "${@}"
    set -- "${1%"${1##[[:digit:]]*}"}" "${@}"
  fi

  set -- "$(eval "version_${5}")" "${@}"

  if [ ! -e "$(command -v "${6}")" ] || [ "${1%[[:space:]]"${2}"}" != "${6}" ]
  then
    shift 7
    while [ ${#} -gt 0 ]
    do
      case "$(shift; printf '%s\n' "${*}")" in
        *'sudo '*) prompt_sudo ;;
        *) ;;
      esac
      NEED_EVAL="${NEED_EVAL-}" run "${1}" "${2}"
      shift 2
    done
  fi
  return 0
}

version_docker ()
{
  if [ -e "$(command -v docker)" ]
  then
    set -- "$(docker --version)"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%,*}"
    printf 'docker %s' "${1}"
  else
    printf 'docker %s' "${NOVERSION}"
  fi
  return 0
}

version_direnv ()
{
  if [ -e "$(command -v direnv)" ] && [ -d "${LOCAL_SRC}/direnv" ]
  then
    set -- "$(_git direnv rev-list --tags --max-count=1)"
    set -- "$(_git direnv describe --tags "${1}")"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%"${1##[[:digit:]]*}"}"
    printf 'direnv %s' "${1}"
  else
    printf 'direnv %s' "${NOVERSION}"
  fi
  return 0
}

version_vim ()
{
  if [ -e "$(command -v vim)" ] && [ -d "${LOCAL_SRC}/vim" ]
  then
    set -- "$(_git vim rev-list --tags --max-count=1)"
    set -- "$(_git vim describe --tags "${1}")"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%"${1##[[:digit:]]*}"}"
    printf 'vim %s' "${1}"
  else
    printf 'vim %s' "${NOVERSION}"
  fi
  return 0
}

version_tig ()
{
  if [ -e "$(command -v tig)" ]
  then
    set -- "${IFS}"
    IFS="${NL}"
    set -- "${1}" $(tig --version)
    IFS="${1}"
    set -- "${2#"${2%%[[:digit:]]*}"}"
    printf 'tig %s' "${1}"
  else
    printf 'tig %s' "${NOVERSION}"
  fi
  return 0
}

version_shellcheck ()
{
  if [ -e "$(command -v shellcheck)" ]
  then
    set -- "${IFS}"
    IFS="${NL}"
    set -- "${1}" $(shellcheck --version)
    IFS="${1}"
    set -- "${3#"${3%%[[:digit:]]*}"}"
    printf 'shellcheck %s' "${1}"
  else
    printf 'shellcheck %s' "${NOVERSION}"
  fi
  return 0
}

version_fff ()
{
  if [ -e "$(command -v fff)" ]
  then
    fff -v | tr -d '\n'
  else
    printf 'fff %s' "${NOVERSION}"
  fi
  return 0
}

version_tmux ()
{
  if [ -e "$(command -v tmux)" ]
  then
    tmux -V | tr -d '\n'
  else
    printf 'tmux %s' "${NOVERSION}"
  fi
  return 0
}

version_pass ()
{
  if [ -e "$(command -v pass)" ]
  then
    set -- "${IFS}"
    IFS="${NL}"
    set -- "${1}" $(pass version)
    IFS="${1}"
    set -- "${5#"${5%%[[:digit:]]*}"}"
    set -- "${1%"${1##*[[:digit:]]}"}"
    printf 'pass %s' "${1}"
  else
    printf 'pass %s' "${NOVERSION}"
  fi
  return 0
}

version_linguist ()
{
  if [ -e "$(command -v github-linguist)" ]
  then
    set -- "$(github-linguist --version)"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    printf 'linguist %s' "${1}"
  else
    printf 'linguist %s' "${NOVERSION}"
  fi
  return 0
}

version_polyglot ()
{
  if [ -d "${LOCAL_SRC}/polyglot" ] && [ -d "${POLYGLOT}" ]
  then
    set -- "$(_git polyglot rev-list --tags --max-count=1)"
    set -- "$(_git polyglot describe --tags "${1}")"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%"${1##[[:digit:]]*}"}"
    printf 'polyglot %s' "${1}"
  else
    printf 'polyglot %s' "${NOVERSION}"
  fi
  return 0
}

version_tpm ()
{
  if [ -d "${LOCAL_SRC}/tpm" ]
  then
    set -- "$(_git tpm rev-list --tags --max-count=1)"
    set -- "$(_git tpm describe --tags "${1}")"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%"${1##[[:digit:]]*}"}"
    printf 'tpm %s' "${1}"
  else
    printf 'tpm %s' "${NOVERSION}"
  fi
  return 0
}

version_vimix ()
{
  if [ -d "${LOCAL_SRC}/vimix" ]
  then
    set -- "$(_git vimix rev-list --tags --max-count=1)"
    set -- "$(_git vimix describe --tags "${1}")"
    set -- "${1#"${1%%[[:digit:]]*}"}"
    set -- "${1%"${1##[[:digit:]]*}"}"
    printf 'vimix %s' "${1}"
  else
    printf 'vimix %s' "${NOVERSION}"
  fi
  return 0
}

sumup ()
{
  printf '\n'
  while [ -n "${1}" ]
  do
    case "${1%%"${SEP}"*}" in
      *"${NOVERSION}"*) printf '%b' "${BLUE}" ;;
      *) if [ "${1%%"${SEP}"*}" != "$(eval "version_${1%%[[:space:]]*}")" ]
         then
           printf '%b' "${GREEN2}"
         else
           printf '%b' "${WHITE}"
         fi ;;
    esac
    printf '%b%s -> ' "${BOLD}" "${1%%"${SEP}"*}"
    eval "version_${1%%[[:space:]]*}"
    set -- "${1#*"${SEP}"}"
    printf '%b\n' "${RESET}"
  done
  printf '\n'
  return 0
}

main ()
{
  set -eu

  prompt_sudo

  # -- ARGS --
  # 1) is GNOME installed ?
  # 2) old versions
  set -- '1' ''

  mkdir -p "${LOCAL}/bin" "${LOCAL}/share" "${LOCAL}/lib" "${LOCAL_SRC}" \
    "${POLYGLOT}" "${TMUXPLUGINS}" "${LOCAL_SH}"

  dashed 'Checking GNOME installation'
  if [ "${XDG_CURRENT_DESKTOP##*:}" = 'GNOME' ] && \
    [ -e "$(command -v gnome-shell)" ]
  then
    success
  else
    error
    set -- '0' "${2}"
  fi

  if [ ${1} -eq 1 ]
  then
    dashed 'Checking GNOME version'
    set -- "$(gnome-shell --version)" "${@}"
    set -- "${1##*[[:space:]]}\n3.30.1\n" "${@}"
    if [ "$(printf '%b' "${1}" | sort -V | head -n1)" = '3.30.1' ]
    then
      success
      shift 2
    else
      error
      gnome-shell --version
      set -- '0' "${4}"
    fi
  fi

  dashed 'Checking bluetooth service'
  if [ -f /etc/init.d/bluetooth ]
  then
    success

    prompt_sudo
    run 'Disabling bluetooth service' "${SUDO} systemctl disable bluetooth.service" \
      '/lib/systemd/systemd-sysv-install disable bluetooth'
  else
    error
    return 1
  fi

  if ! command -v lsb_release > /dev/null
  then
    prompt_sudo
    run 'Updating system' "${UPDATE}"
    install lsb-release
  fi

  RELEASE="$(lsb_release -cs)"
  readonly RELEASE

  dashed 'Checking mesa drivers ppa'
  case "${RELEASE}" in
    focal) PPA_REPO='kisak/kisak-mesa' ;;
    jammy) PPA_REPO='oibaf/graphics-drivers' ;;
    *) error
       printf 'Unknown %s release\n' "${RELEASE}" 1>&2
       return 1 ;;
  esac
  case "$(${POLICY} 2> /dev/null)" in
    *"${PPA_REPO#*/}"*) success ;;
    *) error
       set -f
       ${SUDO} ${ADD_REPO} ppa:${PPA_REPO} > /dev/null
       set +f ;;
  esac

  set -- "${1}" "${2}$(version_docker)${SEP}"
  set -- "${1}" "${2}$(version_direnv)${SEP}"
  set -- "${1}" "${2}$(version_vim)${SEP}"
  set -- "${1}" "${2}$(version_tig)${SEP}"
  set -- "${1}" "${2}$(version_shellcheck)${SEP}"
  set -- "${1}" "${2}$(version_fff)${SEP}"
  set -- "${1}" "${2}$(version_tmux)${SEP}"
  set -- "${1}" "${2}$(version_pass)${SEP}"
  set -- "${1}" "${2}$(version_linguist)${SEP}"
  set -- "${1}" "${2}$(version_polyglot)${SEP}"

  prompt_sudo
  run 'Updating system' "${UPDATE}"

  prompt_sudo
  run 'Upgrading system' "${UPGRADE}"

  prompt_sudo
  run 'Removing unused packages' "${AUTOREMOVE}"

  # for CLI
  install git tree curl jq silversearcher-ag build-essential make autoconf \
    automake cmake redshift kcolorchooser libreoffice-gnome libreoffice \
    gnome-tweaks
  
  # for vimix  
  install gtk2-engines-murrine gtk2-engines-pixbuf

  # for spaceporn
  install libpng-dev libsystemd-dev libglew-dev libx11-dev

  # for password-store
  install xclip

  # for password-store and docker
  install gnupg

  # for linguist
  install ruby-dev libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev

  # for shellcheck
  install cabal-install
  run 'Updating cabal' 'cabal update'
  set -- "${@}" "${IFS}"
  IFS="${NL}"
  set -- "${@}" $(cabal --version)
  IFS="${3}"
  set -- "${1}" "${2}" "${4##*[[:space:]]}"
  if [ "${3%%.*}" -lt 3 ]
  then
    run 'Installing cabal 3' 'cabal install --reinstall cabal-install'
    prompt_sudo
    run 'Creating cabal 3 symbolic link' "sudo ln -s -f ${HOME}/.cabal/bin/cabal $(command -v cabal)"
  fi
  set -- "${1}" "${2}"

  # for docker
  install ca-certificates lsb-release

  # for vim
  install libtool-bin

  # for vim clipboard feature
  install libxt-dev

  # for vim GUI server-client feature
  install libgtk-3-dev

  # for tmux
  install libevent-dev bison

  # for vim, tmux and tig
  install gcc-10 gcc-10-base gcc-10-doc g++-10 libstdc++-10-dev \
    libstdc++-10-doc libncurses-dev

  # for tmux and tig
  install pkg-config

  # for tig documentation
  install asciidoc

  # for .tmux.conf
  install xsel

  dashed 'Resetting GIT safe repositories'
  git config --global --unset-all safe.directory && success || success

  prompt_sudo
  run 'Adding symbolic link to gcc 10 and g++ 10' \
    "${SUDO} ln -f -s $(command -v gcc-10) $(command -v gcc)" \
    "${SUDO} ln -f -s $(command -v g++-10) $(command -v g++)"

  install_docker

  # for docker
  install docker-ce docker-ce-cli containerd.io docker-compose-plugin

  NEED_EVAL="NEED_EVAL${SEP}" git_install 'direnv' \
    'https://github.com/direnv/direnv' 'Installing direnv' \
    "cd ${LOCAL_SRC}/direnv && sudo bash install.sh > /dev/null 2>&1 && cd - > /dev/null"
  git_install 'vim' 'https://github.com/vim/vim' 'Compiling vim' \
    "make --directory ${LOCAL_SRC}/vim" 'Installing vim' \
    "${SUDO} make --directory ${LOCAL_SRC}/vim install"
  git_install 'tig' 'https://github.com/jonas/tig' 'Compiling tig' \
    "make --directory ${LOCAL_SRC}/tig clean all prefix=${LOCAL}" \
    'Installing tig' \
    "make --directory ${LOCAL_SRC}/tig install prefix=${LOCAL}" \
    'Documenting tig' \
    "${SUDO} make --directory ${LOCAL_SRC}/tig install-doc prefix=/usr"
  NEED_EVAL="NEED_EVAL${SEP}" git_install 'shellcheck' \
    'https://github.com/koalaman/shellcheck' 'Installing shellcheck' \
    "cd ${LOCAL_SRC}/shellcheck && cabal install --overwrite-policy=always --installdir=${HOME}/.cabal/bin > /dev/null && cd - > /dev/null"
  NOTAG='true' git_install 'fff' 'https://github.com/dylanaraps/fff' \
    'Installing fff' "make --directory ${LOCAL_SRC}/fff PREFIX=${LOCAL} install"
  NEED_EVAL="NEED_EVAL${SEP}NEED_EVAL${SEP}${SEP}${SEP}" git_install 'tmux' \
    'https://github.com/tmux/tmux' 'Generating tmux configuration' \
    "cd ${LOCAL_SRC}/tmux && sh autogen.sh > /dev/null 2>&1 && cd - > /dev/null" \
    'Configuring tmux' \
    "cd ${LOCAL_SRC}/tmux && ./configure > /dev/null 2>&1 && cd - > /dev/null" \
    'Compiling tmux' "make --directory ${LOCAL_SRC}/tmux > /dev/null 2>&1" \
    'Installing tmux' \
    "${SUDO} make --directory ${LOCAL_SRC}/tmux install > /dev/null"
  NOTAG='true' git_install 'pass' 'https://git.zx2c4.com/password-store' \
    'Installing password-store' \
    "${SUDO} make install --directory ${LOCAL_SRC}/pass"
  NEED_EVAL="NEED_EVAL${SEP}" git_install 'linguist' \
    'https://github.com/github/linguist' \
    'Installing/Updating github-linguist' \
    "if command -v github-linguist; then ${SUDO} gem update github-linguist; else ${SUDO} gem install github-linguist; fi > /dev/null"

  run 'Copying .vimrc' "cp ${DOT_VIMRC} ${HOME}"

  NEED_EVAL="NEED_EVAL${SEP}" NOTAG='true' git_install 'polyglot' \
    'https://github.com/sheerun/vim-polyglot' \
    'Copying polyglot to vim plugins directory' \
    "(set -- ${LOCAL_SRC}/polyglot/*;"' while [ ${#} -gt 0 ]; do case "${1}" in *.git) ;; *) cp -a "${1}"'" ${POLYGLOT} ;; esac; shift; done)"

  run 'Copying .tmux.conf' "cp ${DOT_TMUXCONF} ${HOME}"

  NEED_EVAL="NEED_EVAL${SEP}" NOTAG='true' git_install 'tpm' 'https://github.com/tmux-plugins/tpm' \
    'Copying tpm into .tmux directory' \
    "(set -- ${LOCAL_SRC}/tpm/*;"' while [ ${#} -gt 0 ]; do case "${1}" in *.git) ;; *) cp -a "${1}"'" ${TMUXPLUGINS} ;; esac; shift; done)"

  run 'Installing tmux plugins' "${TMUXPLUGINS}/bin/install_plugins"

  NOTAG='true' git_install 'vimix' \
    'https://github.com/vinceliuice/vimix-gtk-themes' \
    'Installing vimix themes' "sudo ${LOCAL_SRC}/vimix/install.sh -t all -s all"

  NEED_EVAL="${SEP}NEED_EVAL${SEP}" run 'Copying .bashrc' \
    "cp /etc/skel/.bashrc ${HOME}" \
    "cat ${DOT_BASHRC} >> ${HOME}/.bashrc"

  NEED_EVAL="${SEP}NEED_EVAL${SEP}" run 'Copying .bash_profile' \
    "cp /etc/skel/.profile ${HOME}/.bash_profile" \
    "cat ${DOT_PROFILE} >> ${HOME}/.bash_profile"

  run 'Copying .bash_aliases' "cp ${DOT_ALIASES} ${HOME}/.bash_aliases"

  prompt_sudo
  run 'Copying .gitignore' "sudo cp ${DOT_GITIGNORE} ${GITTEMPLATES}"

  prompt_sudo
  run 'Copying hooks' "sudo cp -a ${DOT_HOOKS} ${GITTEMPLATES}"

  run 'Copying scripts' "cp -a ${DOT_SH}/. ${LOCAL_SH}"

  sumup "${2}"

  return 0

  # CTAGS: echo -n -e $(dashed "Checking python3-docutils installation")$' '
  # CTAGS: echo -n -e $(dashed "Checking libseccomp-dev installation")$' '
  # CTAGS: echo -n -e $(dashed "Checking libjansson-dev installation")$' '

  if [[ ${GNOME} -eq 1 ]]; then

    DASHED=$(dashed "Copying scripts")
    [[ $(( $(date +%s) - ${SUDO_START} )) -gt 290 ]] && sudo -k \
      && sudo printf "" && SUDO_START=$(date +%s)
    dots "${DASHED}" &
    DOTS_PID=$!
    for SCRIPT in $(command ls ${DOT_SH}); do
      sudo \cp ${DOT_SH}/${SCRIPT} ${LOCAL_SH} &> /dev/null
    done
    STATUS=$?

    kill ${DOTS_PID} &> /dev/null
    wait ${DOTS_PID} &> /dev/null
    DASHED=${CLEAR}${DASHED}

    if [[ ${STATUS} -eq 0 ]]; then
      echo -e ${DASHED} ${GREEN}"OK"${RESET}
    else
      echo -e ${DASHED} ${RED}"Not OK"${RESET} \
        && pushd -0 &> /dev/null && dirs -c && return 1
    fi

    DASHED=$(dashed "Copying crons")
    [[ $(( $(date +%s) - ${SUDO_START} )) -gt 290 ]] && sudo -k \
      && sudo printf "" && SUDO_START=$(date +%s)
    dots "${DASHED}" &
    DOTS_PID=$!
    [[ $(which crontab | wc -l) -eq 1 ]] && echo "* * * * * env DISPLAY=:0.0\
 sh ${LOCAL_SH}/redshift.sh > /dev/null 2>&1" | crontab - &> /dev/null
    STATUS=$?

    kill ${DOTS_PID} &> /dev/null
    wait ${DOTS_PID} &> /dev/null
    DASHED=${CLEAR}${DASHED}

    if [[ ${STATUS} -eq 0 ]]; then
      echo -e ${DASHED} ${GREEN}"OK"${RESET}
    else
      echo -e ${DASHED} ${RED}"Not OK"${RESET} \
        && pushd -0 &> /dev/null && dirs -c && return 1
    fi

    DASHED=$(dashed "Enabling GNOME extensions")
    dots "${DASHED}" &
    DOTS_PID=$!
    gsettings set org.gnome.shell disable-user-extensions false &> /dev/null
    STATUS=$?

    kill ${DOTS_PID} &> /dev/null
    wait ${DOTS_PID} &> /dev/null
    DASHED=${CLEAR}${DASHED}

    if [[ ${STATUS} -eq 0 ]]; then
      echo -e ${DASHED} ${GREEN}"OK"${RESET}
    else
      echo -e ${DASHED} ${RED}"Not OK"${RESET} \
        && pushd -0 &> /dev/null && dirs -c && return 1
    fi

    DASHED=$(dashed "Hidding desktop icons")
    dots "${DASHED}" &
    DOTS_PID=$!
    gsettings set org.gnome.desktop.background show-desktop-icons false \
      &> /dev/null

    STATUS=$?

    kill ${DOTS_PID} &> /dev/null
    wait ${DOTS_PID} &> /dev/null
    DASHED=${CLEAR}${DASHED}

    if [[ ${STATUS} -eq 0 ]]; then
      echo -e ${DASHED} ${GREEN}"OK"${RESET}
    else
      echo -e ${DASHED} ${RED}"Not OK"${RESET}
    fi

    if [[ $(gnome-extensions list | grep -E "desktop-icons" | wc -l) -eq 1 ]];
      then
        DASHED=$(dashed "Disabling desktop-icons extension")
        dots "${DASHED}" &
        DOTS_PID=$!
        gsettings set org.gnome.shell.extensions.desktop-icons show-home \
          false &> /dev/null && gsettings set \
            org.gnome.shell.extensions.desktop-icons show-trash false \
              &> /dev/null && gnome-extensions disable desktop-icons@csoriano \
                &> /dev/null
        STATUS=$?

        kill ${DOTS_PID} &> /dev/null
        wait ${DOTS_PID} &> /dev/null
        DASHED=${CLEAR}${DASHED}

        if [[ ${STATUS} -eq 0 ]]; then
          echo -e ${DASHED} ${GREEN}"OK"${RESET}
        else
          echo -e ${DASHED} ${RED}"Not OK"${RESET}
        fi
    fi

    DASHED=$(dashed "Setting GNOME Interface")
    dots "${DASHED}" &
    DOTS_PID=$!
    gsettings set org.gnome.desktop.interface show-battery-percentage true \
      &> /dev/null && [[ -f /etc/X11/cursors/redglass.theme ]] \
      && gsettings set org.gnome.desktop.interface cursor-theme 'redglass' \
        &> /dev/null && [[ -d /usr/share/icons/HighContrast ]] \
      && gsettings set org.gnome.desktop.interface gtk-theme \
        'HighContrastInverse' &> /dev/null

    STATUS=$?

    kill ${DOTS_PID} &> /dev/null
    wait ${DOTS_PID} &> /dev/null
    DASHED=${CLEAR}${DASHED}

    if [[ ${STATUS} -eq 0 ]]; then
      echo -e ${DASHED} ${GREEN}"OK"${RESET}
    else
      echo -e ${DASHED} ${RED}"Not OK"${RESET}
    fi

    DASHED=$(dashed "Restarting GNOME")
    echo -n -e "${DASHED}"$' '
    killall -3 gnome-shell &> /dev/null

    if [[ $? -eq 0 ]]; then
      echo -n -e ${GREEN}"OK"${RESET}\
        "\n\n    Press Enter when GNOME service is functional again " \
          && read && echo
    else
      echo -e ${RED}"Not OK"${RESET} && pushd -0 &> /dev/null && dirs -c \
        && return 1
    fi
  fi

  DASHED=$(dashed "Sourcing .bash_profile")
  dots "${DASHED}" &
  DOTS_PID=$!
  source ${HOME}/.bash_profile &> /dev/null
  STATUS=$?

  kill ${DOTS_PID} &> /dev/null
  wait ${DOTS_PID} &> /dev/null
  DASHED=${CLEAR}${DASHED}

  if [[ ${STATUS} -eq 0 ]]; then
    echo -e ${DASHED} ${GREEN}"OK"${RESET}
  else
    echo -e ${DASHED} ${RED}"Not OK"${RESET} && pushd -0 &> /dev/null \
      && dirs -c && return 1
  fi

  DASHED=$(dashed "Reloading CRON service")
  [[ $(( $(date +%s) - ${SUDO_START} )) -gt 290 ]] && sudo -k \
    && sudo printf "" && SUDO_START=$(date +%s)
  dots "${DASHED}" &
  DOTS_PID=$!
  sudo service cron reload &> /dev/null
  STATUS=$?

  kill ${DOTS_PID} &> /dev/null
  wait ${DOTS_PID} &> /dev/null
  DASHED=${CLEAR}${DASHED}

  if [[ ${STATUS} -eq 0 ]]; then
    echo -e ${DASHED} ${GREEN}"OK"${RESET}
  else
    echo -e ${DASHED} ${RED}"Not OK"${RESET} && pushd -0 &> /dev/null \
      && dirs -c && return 1
  fi

  echo -n -e $(dashed "Checking Crocus driver usage")$' '
  [[ $(( $(date +%s) - ${SUDO_START} )) -gt 290 ]] && sudo -k \
    && sudo printf "" && SUDO_START=$(date +%s)
  if [[ $(sudo cat /etc/environment \
    | grep -E "MESA_LOADER_DRIVER_OVERRIDE=crocus" | wc -l ) -eq 1 ]]; then
      echo -e ${GREEN}"OK"${RESET}
  else
    echo -e ${RED}"Not OK"${RESET}
    sudo bash -c "echo 'MESA_LOADER_DRIVER_OVERRIDE=crocus' >> /etc/environment"
    REBOOT=1
  fi

  echo -n -e $(dashed "Checking DRI3 usage")$' '
  [[ $(( $(date +%s) - ${SUDO_START} )) -gt 290 ]] && sudo -k \
    && sudo printf "" && SUDO_START=$(date +%s)
  if [[ -f /etc/X11/xorg.conf.d/20-intel.conf && \
    $(sudo cat /etc/X11/xorg.conf.d/20-intel.conf | grep -E "DRI" \
    | grep -E "3" | wc -l ) -eq 1 ]]; then
      echo -e ${GREEN}"OK"${RESET}
  else
    echo -e ${RED}"Not OK"${RESET}
    sudo mkdir -p /etc/X11/xorg.conf.d && sudo bash -c \
      "echo -e 'Section \"Device\"\n   Identifier  \"Intel Graphics\"\n   Driver      \"intel\"\n   Option      \"DRI\"    \"3\"\nEndSection' >> /etc/X11/xorg.conf.d/20-intel.conf"
    REBOOT=1
  fi

  [[ ${REBOOT} -gt 0 ]] \
    && echo -e "${YELLOW}Some configuration files have been modified and need a reboot to be used${RESET}"

  pushd -0 &> /dev/null && dirs -c
}

main
