#!/bin/bash

TYPE="(fixing|feature|update|refactoring)"
REGEX='(\['${TYPE}' - [^[:space:]]+\]|'
REGEX=${REGEX}'\['${TYPE}' - [^[:space:]]+\][[:space:]][^[:space:]].*|'
REGEX=${REGEX}'\['${TYPE}'\][[:space:]][^[:space:]].*)'

if ! grep -ixqE "$REGEX" "$1"; then
  echo "Unexpected commit message: [<type> - <identifier>] <message>" >&2
  exit 1
fi

