#!/usr/bin/env bash

TYPE="(fixing|update|refactoring|merge)"
REGEX='(\['${TYPE}' - [^[:space:]].*\]|'
REGEX=${REGEX}'\['${TYPE}' - [^[:space:]].*\][[:space:]][^[:space:]].*|'
REGEX=${REGEX}'\['${TYPE}'\][[:space:]][^[:space:]].*)'

if ! grep -ixqE "$REGEX" "$1"; then
  echo "Unexpected commit message: [<type> - <identifier>] <message>" >&2
  echo "Expected types:$(echo ${TYPE} | sed 's/[()|]/ /g')"
  exit 1
fi

