#!/usr/bin/env bash

TYPE="(fixing|update|refactoring|merge)"
REGEX='(\['${TYPE}' - [^[:space:]].*\]|'
REGEX=${REGEX}'\['${TYPE}' - [^[:space:]].*\][[:space:]][^[:space:]].*|'
REGEX=${REGEX}'\['${TYPE}'\][[:space:]][^[:space:]].*)'

if ! grep -ixqE "$REGEX" "$1"; then
  echo -e "Expected commit messages:\n"\
    "- \"[<type> - <identifier>] <message>\"\n"\
    "- \"[<type> - <identifier>]\"\n"\
    "- \"[<type>] <message>\"\n\nExpected types:"\
    "$(echo -e ${TYPE//[(|]/\\n - } | tr -d ')')"
  exit 1
fi
