#! /bin/sh
# shellcheck disable=2034,2154
# SC2034: VAR appears unused => VAR used for templating
# SC2154: VAR is referenced but not assigned => VAR is assigned with eval statement in 01init.sh function

_DOCKER_NET="${_DOCKER_ID}"
JUMP_AREA_NET='jump-area'
PROXIFIED_DOCKER_SOCKET_NET="proxified-${_DOCKER_ID}-socket"

# shellcheck disable=2153
# SC2153: Possible misspelling => it is not, we really want PROXY_ID here
PROXIFIED_XSERVER_SOCKET_NET="proxified-${XSERVER_ID}-socket"

SUBNET_MASK='/24'

NET_PFX='172.17'
PROXIFIED_DOCKER_SOCKET_PFX="${NET_PFX}.1"
_DOCKER_PFX="${NET_PFX}.2"
PROXIFIED_XSERVER_SOCKET_PFX="${NET_PFX}.3"
JUMP_AREA_PFX="${NET_PFX}.4"

_DOCKER_SUB="${_DOCKER_PFX}.0${SUBNET_MASK}"
JUMP_AREA_SUB="${JUMP_AREA_PFX}.0${SUBNET_MASK}"
PROXIFIED_DOCKER_SOCKET_SUB="${PROXIFIED_DOCKER_SOCKET_PFX}.0${SUBNET_MASK}"
PROXIFIED_XSERVER_SOCKET_SUB="${PROXIFIED_XSERVER_SOCKET_PFX}.0${SUBNET_MASK}"

JUMP_AREA_GATEWAY_IP="${JUMP_AREA_PFX}.1"
PROXIFIED_DOCKER_SOCKET_GATEWAY_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.1"
PROXY_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.2"
LISTENER_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.3"
CONTROLLER_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.4"
PROXIFIED_XSERVER_SOCKET_GATEWAY_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.1"
XSERVER_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.2"
SPACEPORN_RELAY_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.3"
_DOCKER_GATEWAY_IP="${_DOCKER_PFX}.1"
CLIENT_IP="${_DOCKER_PFX}.2"
REGISTRY_IP="${_DOCKER_PFX}.3"
BUILDER_IP="${_DOCKER_PFX}.4"
