#! /bin/sh

JUMP_AREA_NET='jump-area'
PROXIFIED_SOCKET_NET='proxified-socket'

SUBNET_MASK='/24'

PROXY_PORT='2363'

NET_PFX='172.17'
PROXIFIED_SOCKET_PFX="${NET_PFX}.1"
JUMP_AREA_PFX="${NET_PFX}.2"

PROXIFIED_SOCKET_SUB="${PROXIFIED_SOCKET_PFX}.0${SUBNET_MASK}"
JUMP_AREA_SUB="${JUMP_AREA_PFX}.0${SUBNET_MASK}"

DOCKER_HOST="${PROXY_ID}:${PROXY_PORT}"
HTTP_DOCKER_HOST="http://${DOCKER_HOST}"
TCP_DOCKER_HOST="tcp://${DOCKER_HOST}"

PROXIFIED_SOCKET_GATEWAY_IP="${PROXIFIED_SOCKET_PFX}.1"
JUMP_AREA_GATEWAY_IP="${JUMP_AREA_PFX}.1"
PROXY_IP="${PROXIFIED_SOCKET_PFX}.2"
COLLECTOR_IP="${PROXIFIED_SOCKET_PFX}.3"
CONTROLLER_IP="${PROXIFIED_SOCKET_PFX}.4"
