#! /bin/sh
# shellcheck disable=2034,2154
# SC2034: VAR appears unused => VAR used for templating
# SC2154: VAR is referenced but not assigned => VAR is assigned with eval statement in 01init.sh function

BUILDER_NET=${BUILDER_ID}
JUMP_AREA_NET='jump-area'
PROXIFIED_DOCKER_SOCKET_NET="proxified-${_DOCKER_ID}-socket"
PROXIFIED_XSERVER_SOCKET_NET="proxified-${XSERVER_ID}-socket"
REGISTRY_NET="${REGISTRY_ID}"

SUBNET_MASK='/24'

NET_PFX='172.17'
PROXIFIED_DOCKER_SOCKET_PFX="${NET_PFX}.1"
BUILDER_PFX="${NET_PFX}.2"
REGISTRY_PFX="${NET_PFX}.3"
PROXIFIED_XSERVER_SOCKET_PFX="${NET_PFX}.4"
JUMP_AREA_PFX="${NET_PFX}.5"

BUILDER_SUB="${BUILDER_PFX}.0${SUBNET_MASK}"
JUMP_AREA_SUB="${JUMP_AREA_PFX}.0${SUBNET_MASK}"
PROXIFIED_DOCKER_SOCKET_SUB="${PROXIFIED_DOCKER_SOCKET_PFX}.0${SUBNET_MASK}"
PROXIFIED_XSERVER_SOCKET_SUB="${PROXIFIED_XSERVER_SOCKET_PFX}.0${SUBNET_MASK}"
REGISTRY_SUB="${REGISTRY_PFX}.0${SUBNET_MASK}"

BUILDER_GATEWAY_IP="${BUILDER_PFX}.1"
JUMP_AREA_GATEWAY_IP="${JUMP_AREA_PFX}.1"
PROXIFIED_DOCKER_SOCKET_GATEWAY_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.1"
PROXIFIED_XSERVER_SOCKET_GATEWAY_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.1"
REGISTRY_GATEWAY_IP="${REGISTRY_PFX}.1"
PROXY_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.2"
LISTENER_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.3"
CONTROLLER_IP="${PROXIFIED_DOCKER_SOCKET_PFX}.4"
XSERVER_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.2"
SPACEPORN_RELAY_IP="${PROXIFIED_XSERVER_SOCKET_PFX}.3"
