name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: wget the repository
        shell: bash
        run: |
          script="$(mktemp).sh"
          wget -q -O "${script}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
          chmod 0700 "${script}"
          sh -x "${script}" --no-attach
