name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  wget_me:
    strategy:
      matrix:
        pkg:
        - bash
        - dash
        - busybox
        - yash
        - zsh
        - ksh93u+m
        - mksh
        - oksh
        - loksh
    runs-on: ubuntu-latest
    steps:
    - name: check wget_me.sh
      env:
        PKG: ${{ matrix.pkg }}
      shell: bash
      run: |
        set -eux
        tmp="$(mktemp /tmp/tmp.XXXXXXXXXX.sh)"
        OPTS="-x ${tmp} --branch ${GITHUB_HEAD_REF} --runner-is-a-bot"
        wget -q -O "${tmp}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
        chmod 0700 "${tmp}"
        dpkg -s "${PKG}" > /dev/null 2>&1 || sudo apt-get update -y
        if [[ -z "$(apt-cache search --names-only "^${PKG//+/[+]}$")" ]]
        then
          case "${PKG}" in
          ( 'loksh' ) EXE='ksh' ;;
          ( * ) EXE="${PKG}" ;;
          esac
          docker run --volume /var/run/docker.sock:/var/run/docker.sock:ro \
                     --volume "${tmp}:${tmp}:rw" --rm docker:dind \
                     sh -c "apk add --no-cache coreutils sudo git ${PKG}; exec ${EXE} ${OPTS}"
        else
          dpkg -s "${PKG}" > /dev/null 2>&1 || sudo apt-get install -y "${PKG}"
          case "${PKG}" in
          ( 'bash' ) EXE="${PKG} --posix" ;;
          ( 'busybox' ) EXE="${PKG} sh" ;;
          ( 'ksh93u+m' ) EXE='ksh93' ;;
          ( 'zsh' ) EXE="${PKG} --emulate sh" ;;
          ( * ) EXE="${PKG}" ;;
          esac
          ${EXE} ${OPTS}
        fi
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: shellcheck
      shell: bash
      run: |
        shellcheck --severity style --external-sources ./env.sh --external-sources ./env.d/*.sh wget_me.sh
