name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  wget_me:
    strategy:
      matrix:
        shell:
        - bash
        - dash
        - busybox
        - yash
        - zsh
        - ksh93u+m
        - mksh
        - oksh
        - loksh
    runs-on: ubuntu-latest
    steps:
    - name: check wget_me.sh
      env:
        SH: ${{ matrix.shell }}
      shell: bash
      run: |
        script="$(mktemp).sh"
        OPTS="${script} --branch ${GITHUB_HEAD_REF} --runner-is-a-bot"
        wget -q -O "${script}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
        chmod 0700 "${script}"
        sudo apt-get update -y
        if [[ -z "$(apt-cache search --names-only "^${SH}$")" ]]
        then
          case "${SH}" in
          ( 'oksh' ) EXE='ksh' ;;
          ( 'loksh' ) EXE='ksh' ;;
          ( * ) ;;
          esac
          docker run --rm --volume .:/root alpine:latest sh -c "apk add --no-cache ${SH}; ${EXE} -x /root/${OPTS}"
        else
          sudo apt-get install -y "${SH}"
          case "${SH}" in
          ( 'bash' ) SH="${SH} --posix" ;;
          ( 'busybox' ) SH="${SH} sh" ;;
          ( 'ksh93u+m' ) SH='ksh93' ;;
          ( 'zsh' ) SH="${SH} --emulate sh" ;;
          ( * ) ;;
          esac
          ${SH} -x ${OPTS}
        fi
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: shellcheck
      shell: bash
      run: |
        shellcheck --severity style --external-sources ./env.sh --external-sources ./env.d/*.sh wget_me.sh
