name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: wget the repository
        shell: bash
        run: |
          wget -q -O- "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh" | sh -s -- --no-attach
