name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  wget_me:
    strategy:
      matrix:
        shell:
        - bash
        - dash
        - busybox
        - yash
        - zsh
        - ksh93u+m
        - mksh
    runs-on: ubuntu-latest
    steps:
    - name: check wget_me.sh
      env:
        SH: ${{ matrix.shell }}
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y "${SH}"
        script="$(mktemp).sh"
        wget -q -O "${script}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
        chmod 0700 "${script}"
        case "${SH}" in
        ( 'bash' ) SH="${SH} --posix" ;;
        ( 'busybox' ) SH="${SH} sh" ;;
        ( 'ksh93u+m' ) SH='ksh93' ;;
        ( 'zsh' ) SH="${SH} --emulate sh" ;;
        ( * ) ;;
        esac
        ${SH} -x "${script}" --branch "${GITHUB_HEAD_REF}" --runner-is-a-bot 
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: shellcheck
      shell: bash
      run: |
        shellcheck --shell sh -x ./env.sh ./wget_me.sh
