name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        shell: bash
        run: |
          # remove this task later (when a more recent docker version will be used into Github Actions images)
          sudo rm -f "$(command -v docker)"

      - name: check wget_me.sh
        shell: bash
        run: |
          script="$(mktemp).sh"
          wget -q -O "${script}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
          chmod 0700 "${script}"
          sh -x "${script}" --no-attach "${GITHUB_HEAD_REF}"
