name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  wget_me-alpine:
    strategy:
      matrix:
        pkg:
        - busybox
        - oksh
        - loksh
    runs-on: ubuntu-latest
    container: docker:dind
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
    - name: check wget_me.sh
      env:
        PKG: ${{ matrix.pkg }}
      shell: sh
      run: |
        set -eux
        apk add --no-cache coreutils sudo git
        tmp="$(mktemp /tmp/tmp.XXXXXXXXXX.sh)"
        wget -q -O "${tmp}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
        chmod 0700 "${tmp}"
        case "${PKG}" in
        ( 'busybox' ) EXE="${PKG} sh" ;;
        ( 'loksh' ) apk add --no-cache "${PKG}"; EXE='ksh' ;;
        ( * ) apk add --no-cache "${PKG}"; EXE="${PKG}" ;;
        esac
        ${EXE} -x ${tmp} --branch ${GITHUB_HEAD_REF} --runner-is-a-bot
  wget_me-ubuntu:
    strategy:
      matrix:
        pkg:
        - bash
        - dash
        - yash
        - zsh
        - ksh93u+m
        - mksh
    runs-on: ubuntu-latest
    steps:
    - name: check wget_me.sh
      env:
        PKG: ${{ matrix.pkg }}
      shell: bash
      run: |
        set -eux
        tmp="$(mktemp /tmp/tmp.XXXXXXXXXX.sh)"
        wget -q -O "${tmp}" "https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_HEAD_REF}/wget_me.sh"
        chmod 0700 "${tmp}"
        dpkg -s "${PKG}" > /dev/null 2>&1 || sudo apt-get update -y
        dpkg -s "${PKG}" > /dev/null 2>&1 || sudo apt-get install -y "${PKG}"
        case "${PKG}" in
        ( 'bash' ) EXE="${PKG} --posix" ;;
        ( 'ksh93u+m' ) EXE='ksh93' ;;
        ( 'zsh' ) EXE="${PKG} --emulate sh" ;;
        ( * ) EXE="${PKG}" ;;
        esac
        ${EXE} -x ${tmp} --branch ${GITHUB_HEAD_REF} --runner-is-a-bot
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: shellcheck
      shell: bash
      run: |
        shellcheck --severity style --external-sources ./env.sh --external-sources ./env.d/*.sh wget_me.sh
